org: arcelabs
app: auth-service
service: auth-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
